# Generated by Django 4.2.5 on 2023-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('batch_id', models.CharField(max_length=50)),
                ('slowLearner', models.CharField(max_length=20)),
            ],
        ),
    ]
