# Generated by Django 4.2.5 on 2023-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='predictedScore',
            field=models.CharField(default='', max_length=20),
        ),
    ]
