# Generated by Django 4.2.5 on 2023-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_feature1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature1',
        ),
    ]
