# Generated by Django 4.2.5 on 2023-10-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_btech_delete_feature1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Btech',
            new_name='Students',
        ),
    ]
