# Generated by Django 4.2.5 on 2023-10-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_btech_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
