# Generated by Django 4.2.5 on 2023-10-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_rename_students_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
