# Generated by Django 4.2.5 on 2023-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_ram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.AddField(
            model_name='students',
            name='btech',
            field=models.JSONField(default={'key': 'default_value'}),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='s_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
