# Generated by Django 4.2.5 on 2023-10-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_delete_ram_students_btech_students_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='btech',
            field=models.JSONField(default=dict),
        ),
    ]
